### ISSUE TITLE
where the beemovie-bot

### ISSUE THREAD

**Issue by pawelk1337** [DrSquidX/Discord-Bots#1]

**Comment by DrSquidX** [comment]
Not sure. How ever it is very easy to make a bot that spams the script!
```
async def on_ready():
    file = open("beemovie.txt","r")
    channel = await client.fetch_channel(0000) # Change the 0's into an actual channel id
    for i in file.readlines():
        await channel.send(i)
```
Make sure you have all of the discord imports and everything needed(this is just a snippet). - You were also able to dig up one of my older scripts.

**Comment by pawelk1337** [comment]
thx
